import { createReadStream } from 'node:fs';
import type { FastifyInstance } from 'fastify';
import { cancelAiVideoJob, createAiVideoJob, getAiVideoClip, getAiVideoJob, getAiVideoResult, resumeAiVideoJob, type CreateAiVideoInput } from '../services/aiVideoJobs';
import { flowAgentStatus } from '../services/googleFlow';
import { openFlowBrowser } from '../services/flowBrowser';
export async function aiVideoRoutes(app: FastifyInstance) {
  app.get('/api/ai-video/flow-agent/status', async () => flowAgentStatus());
  app.post('/api/ai-video/flow-agent/open', async (_request, reply) => { try { await openFlowBrowser(); return flowAgentStatus(); } catch (error) { return reply.code(500).send({ error: error instanceof Error ? error.message : 'Không thể mở Google Flow cùng extension Flow Agent.' }); } });
  app.post('/api/ai-video/jobs', async (request, reply) => { try { return reply.code(202).send(await createAiVideoJob(request.body as CreateAiVideoInput)); } catch (error) { return reply.code(400).send({ error: error instanceof Error ? error.message : 'Không thể tạo AI video job.' }); } });
  app.get('/api/ai-video/jobs/:id', async (request, reply) => { try { return await getAiVideoJob(String((request.params as { id?: string }).id || '')); } catch { return reply.code(404).send({ error: 'Không tìm thấy AI video job.' }); } });
  app.post('/api/ai-video/jobs/:id/cancel', async (request, reply) => { try { return await cancelAiVideoJob(String((request.params as { id?: string }).id || '')); } catch { return reply.code(404).send({ error: 'Không tìm thấy AI video job.' }); } });
  app.post('/api/ai-video/jobs/:id/resume', async (request, reply) => { try { const body = request.body as CreateAiVideoInput; return reply.code(202).send(await resumeAiVideoJob(String((request.params as { id?: string }).id || ''), body?.model, body?.script)); } catch (error) { return reply.code(400).send({ error: error instanceof Error ? error.message : 'Không thể tiếp tục AI video job.' }); } });
  app.get('/api/ai-video/jobs/:id/video', async (request, reply) => { try { const result = await getAiVideoResult(String((request.params as { id?: string }).id || '')); reply.header('Content-Type', 'video/mp4').header('Content-Length', String(result.size)); return reply.send(createReadStream(result.path)); } catch { return reply.code(404).send({ error: 'Video AI chưa sẵn sàng.' }); } });
  app.get('/api/ai-video/jobs/:id/clips/:sceneIndex', async (request, reply) => { try { const params = request.params as { id?: string; sceneIndex?: string }; const sceneIndex = Number(params.sceneIndex); if (!Number.isInteger(sceneIndex) || sceneIndex < 1) throw new Error('Invalid scene index'); const result = await getAiVideoClip(String(params.id || ''), sceneIndex); reply.header('Content-Type', 'video/mp4').header('Content-Length', String(result.size)).header('Accept-Ranges', 'bytes'); if ((request.query as { download?: string })?.download === '1') reply.header('Content-Disposition', `attachment; filename="ai-video-scene-${String(sceneIndex).padStart(2, '0')}.mp4"`); return reply.send(createReadStream(result.path)); } catch { return reply.code(404).send({ error: 'Cảnh video chưa sẵn sàng.' }); } });
}
