import { createReadStream } from 'node:fs';
import type { FastifyInstance } from 'fastify';
import { cancelAiVideoJob, createAiVideoJob, getAiVideoClip, getAiVideoJob, getAiVideoResult, resumeAiVideoJob, type CreateAiVideoInput } from '../services/aiVideoJobs';
import { closeFlowBrowser, flowBrowserStatus, inspectFlowBrowser, openFlowBrowser } from '../services/flowBrowser';
import { completeFlowBridgeVideo, failFlowBridgeCommand, flowBridgeStatus, inspectFlowBridge, updateFlowBridge } from '../services/flowBridge';
export async function aiVideoRoutes(app: FastifyInstance) {
  app.addContentTypeParser('application/octet-stream', { parseAs: 'buffer' }, (_request, body, done) => done(null, body));
  app.post('/api/ai-video/flow-bridge/heartbeat', async (request) => updateFlowBridge(request.body as { url?: string; title?: string; controls?: Array<{ tag: string; text: string; ariaLabel: string; placeholder: string }> }));
  app.get('/api/ai-video/flow-bridge/status', async () => flowBridgeStatus());
  app.get('/api/ai-video/flow-bridge/inspect', async () => inspectFlowBridge());
  app.post('/api/ai-video/flow-bridge/commands/:id/video', async (request, reply) => { try { return await completeFlowBridgeVideo(String((request.params as { id?: string }).id || ''), request.body as Buffer); } catch (error) { return reply.code(400).send({ error: error instanceof Error ? error.message : 'Không nhận được video Flow.' }); } });
  app.post('/api/ai-video/flow-bridge/commands/:id/fail', async (request) => failFlowBridgeCommand(String((request.params as { id?: string }).id || ''), String((request.body as { error?: string })?.error || '')));
  app.get('/api/ai-video/flow-browser/status', async () => flowBrowserStatus());
  app.post('/api/ai-video/flow-browser/open', async (_request, reply) => { try { return await openFlowBrowser(); } catch (error) { return reply.code(500).send({ error: error instanceof Error ? error.message : 'Không thể mở Cốc Cốc.' }); } });
  app.post('/api/ai-video/flow-browser/close', async () => closeFlowBrowser());
  app.get('/api/ai-video/flow-browser/inspect', async () => inspectFlowBrowser());
  app.post('/api/ai-video/jobs', async (request, reply) => { if (!flowBridgeStatus().connected) return reply.code(409).send({ error: 'Chưa kết nối tab Google Flow. Hãy cài AutoSub Flow Bridge và giữ tab Flow đang mở.' }); try { return reply.code(202).send(await createAiVideoJob(request.body as CreateAiVideoInput)); } catch (error) { return reply.code(400).send({ error: error instanceof Error ? error.message : 'Không thể tạo AI video job.' }); } });
  app.get('/api/ai-video/jobs/:id', async (request, reply) => { try { return await getAiVideoJob(String((request.params as { id?: string }).id || '')); } catch { return reply.code(404).send({ error: 'Không tìm thấy AI video job.' }); } });
  app.post('/api/ai-video/jobs/:id/cancel', async (request, reply) => { try { return await cancelAiVideoJob(String((request.params as { id?: string }).id || '')); } catch { return reply.code(404).send({ error: 'Không tìm thấy AI video job.' }); } });
  app.post('/api/ai-video/jobs/:id/resume', async (request, reply) => { try { const body = request.body as CreateAiVideoInput; return reply.code(202).send(await resumeAiVideoJob(String((request.params as { id?: string }).id || ''), body?.flowCredentials, body?.model, body?.script)); } catch (error) { return reply.code(400).send({ error: error instanceof Error ? error.message : 'Không thể tiếp tục AI video job.' }); } });
  app.get('/api/ai-video/jobs/:id/video', async (request, reply) => { try { const result = await getAiVideoResult(String((request.params as { id?: string }).id || '')); reply.header('Content-Type', 'video/mp4').header('Content-Length', String(result.size)); return reply.send(createReadStream(result.path)); } catch { return reply.code(404).send({ error: 'Video AI chưa sẵn sàng.' }); } });
  app.get('/api/ai-video/jobs/:id/clips/:sceneIndex', async (request, reply) => { try { const params = request.params as { id?: string; sceneIndex?: string }; const sceneIndex = Number(params.sceneIndex); if (!Number.isInteger(sceneIndex) || sceneIndex < 1) throw new Error('Invalid scene index'); const result = await getAiVideoClip(String(params.id || ''), sceneIndex); reply.header('Content-Type', 'video/mp4').header('Content-Length', String(result.size)).header('Accept-Ranges', 'bytes'); if ((request.query as { download?: string })?.download === '1') reply.header('Content-Disposition', `attachment; filename="ai-video-scene-${String(sceneIndex).padStart(2, '0')}.mp4"`); return reply.send(createReadStream(result.path)); } catch { return reply.code(404).send({ error: 'Cảnh video chưa sẵn sàng.' }); } });
}
