import { chromium } from 'playwright-core';
import assert from 'node:assert/strict';
import { mkdir } from 'node:fs/promises';
const browser = await chromium.launch({ executablePath: 'C:/Program Files/Google/Chrome/Application/chrome.exe', headless: true });
try {
  const page = await browser.newPage({ viewport: { width: 1440, height: 950 } });
  const errors: string[] = []; page.on('pageerror', (error) => errors.push(error.message));
  let graph = { nodes: [], edges: [] };
  await page.route('**/api/manual-film/**', async (route) => { if (route.request().method() === 'PUT') graph = route.request().postDataJSON(); return route.fulfill({ json: graph }); });
  await page.goto('http://localhost:5173');
  await page.getByRole('button', { name: /AI Video Studio/ }).click();
  await page.getByRole('button', { name: /^Thủ công/ }).click();
  const canvas = page.locator('.manual-film');
  await canvas.getByRole('button', { name: 'Thêm node', exact: true }).click();
  await canvas.getByRole('button', { name: 'Kịch bản', exact: true }).click();
  await canvas.locator('article').nth(0).waitFor();
  await canvas.getByRole('button', { name: 'Kịch bản', exact: true }).click();
  await canvas.locator('article').nth(1).waitFor();
  await canvas.getByRole('button', { name: 'Storyboard', exact: true }).click();
  await canvas.locator('article').nth(2).waitFor();
  assert.equal(await canvas.locator('article').count(), 3);
  await canvas.getByRole('button', { name: 'Thêm node', exact: true }).click();
  await canvas.locator('article').nth(0).locator('.ai-flow-node-copy').click();
  const inspector = canvas.getByRole('complementary', { name: 'Chỉnh sửa node' });
  await inspector.getByLabel('Prompt').fill('Một khu rừng lúc bình minh');
  await inspector.getByRole('button', { name: 'Lưu thay đổi' }).click();
  await inspector.getByRole('button', { name: 'Đóng bảng node' }).click();
  assert.equal(await canvas.locator('article textarea').count(), 0);
  await canvas.locator('article').nth(0).getByRole('button', { name: 'Đầu ra node 1' }).click();
  await canvas.locator('article').nth(2).getByRole('button', { name: 'Đầu vào node 3' }).click();
  await canvas.getByRole('button', { name: 'Lưu workflow' }).click();
  assert.equal(graph.edges.length, 1);
  await canvas.locator('article').nth(2).locator('.ai-flow-node-media').click();
  await inspector.getByLabel('Prompt').fill('Ánh nắng xuyên qua lá');
  await inspector.getByRole('button', { name: 'Lưu thay đổi' }).click();
  await mkdir('artifacts/manual-film', { recursive: true });
  await page.screenshot({ path: 'artifacts/manual-film/canvas.png' });
  await canvas.getByRole('button', { name: 'Ngắt nguồn #1 ×' }).click();
  await canvas.getByRole('button', { name: 'Lưu workflow' }).click();
  assert.equal(graph.edges.length, 0);
  await inspector.getByRole('button', { name: 'Đóng bảng node' }).click();
  await canvas.getByRole('button', { name: 'Thêm node', exact: true }).click();
  await canvas.getByRole('button', { name: 'Gộp video', exact: true }).click();
  await canvas.locator('article').nth(3).waitFor();
  await canvas.getByRole('button', { name: 'Đóng thư viện node' }).click();
  for (const article of await canvas.locator('article').all()) {
    const geometry = await article.evaluate((el) => ({ bottom: el.getBoundingClientRect().bottom, footer: el.querySelector('footer')?.getBoundingClientRect().bottom }));
    if (geometry.footer) assert.ok(geometry.footer < geometry.bottom, 'Footer must stay inside the bottom border');
  }
  await canvas.locator('article').nth(3).locator('.ai-flow-node-media').click();
  assert.equal(await inspector.getByLabel('Prompt', { exact: true }).count(), 0);
  await inspector.getByRole('button', { name: 'Bắt đầu ghép' }).click();
  await canvas.getByRole('alert').filter({ hasText: 'Nối các node video' }).waitFor();
  await canvas.getByRole('button', { name: 'Đóng thông báo' }).click();
  await page.screenshot({ path: 'artifacts/manual-film/merge.png' });
  page.once('dialog', (dialog) => dialog.accept());
  await canvas.getByRole('button', { name: 'Xóa tất cả node' }).click();
  await canvas.locator('article').waitFor({ state: 'hidden' });
  assert.equal(graph.nodes.length, 0);
  assert.deepEqual(errors, []);
  console.log('PASS manual UI: add multiple scripts, connect/disconnect, save, clear all. No generation.');
} finally { await browser.close(); }
