import { randomUUID } from 'node:crypto';
import { writeFile } from 'node:fs/promises';

const generateUrl = 'https://aisandbox-pa.googleapis.com/v1/video:batchAsyncGenerateVideoText';
const checkUrl = 'https://aisandbox-pa.googleapis.com/v1/video:batchCheckAsyncVideoGenerationStatus';
export const FLOW_VIDEO_MODELS = ['Omni Flash', 'Veo 3.1 - Fast', 'Veo 3.1 - Lite', 'Veo 3.1 - Quality', 'Veo 3.1 - Lite [Lower Priority]'] as const;
export type FlowVideoModel = typeof FLOW_VIDEO_MODELS[number];
type FlowCredentials = { nanoApiKey?: string; veoToken?: string; veoCookie?: string };
export type FlowVideoAspectRatio = '9:16' | '16:9';
const directModelKeys: Partial<Record<FlowVideoModel, string>> = { 'Veo 3.1 - Lite [Lower Priority]': 'veo_3_1_t2v_lite_4s_low_priority' };

function walk(value: unknown, visit: (node: Record<string, unknown>) => void) { if (!value || typeof value !== 'object') return; if (Array.isArray(value)) { value.forEach((item) => walk(item, visit)); return; } const node = value as Record<string, unknown>; visit(node); Object.values(node).forEach((item) => walk(item, visit)); }
function mediaEntries(value: unknown, fallbackProjectId: string) { const entries: Array<{ name: string; projectId: string; status: string; url?: string }> = []; walk(value, (node) => { const status = String(node.mediaGenerationStatus || ''); const name = String(node.name || node.mediaId || node.mediaGenerationId || node.sceneId || ''); if (!status || !name) return; const url = [node.mediaUrl, node.videoUrl, node.downloadUri, node.uri].find((item) => typeof item === 'string' && /^https?:\/\//i.test(item)) as string | undefined; entries.push({ name, projectId: String(node.projectId || fallbackProjectId), status: status.replace(/^MEDIA_GENERATION_STATUS_/i, '').toUpperCase(), url }); }); return entries; }
function findDownloadUrl(value: unknown) { let result = ''; walk(value, (node) => { if (result) return; const candidate = [node.mediaUrl, node.videoUrl, node.downloadUri, node.signedUri, node.uri].find((item) => typeof item === 'string' && /^https?:\/\//i.test(item)); if (candidate) result = String(candidate); }); return result; }
async function googleRequest(url: string, token: string, cookie: string, body: unknown, signal?: AbortSignal) { const response = await fetch(url, { method: 'POST', signal, headers: { Authorization: `Bearer ${token}`, 'Content-Type': 'application/json', ...(cookie ? { Cookie: cookie } : {}) }, body: JSON.stringify(body) }); const text = await response.text(); let value: any; try { value = text ? JSON.parse(text) : {}; } catch { value = { raw: text }; } if (!response.ok) throw new Error(`Google Flow Direct HTTP ${response.status}: ${String(value?.error?.message || value?.message || text || response.statusText)}`); return value; }
const delay = (ms: number, signal?: AbortSignal) => new Promise<void>((resolve, reject) => { const timer = setTimeout(resolve, ms); signal?.addEventListener('abort', () => { clearTimeout(timer); reject(new DOMException('Đã dừng tác vụ.', 'AbortError')); }, { once: true }); });

export async function generateGoogleFlowVideo(prompt: string, outputFile: string, model: FlowVideoModel = 'Veo 3.1 - Lite [Lower Priority]', credentials?: FlowCredentials, _referenceImagePath?: string, aspectRatio: FlowVideoAspectRatio = '9:16', signal?: AbortSignal) {
  const token = credentials?.veoToken?.trim() || process.env.VEO_TOKEN?.trim(); const cookie = credentials?.veoCookie?.trim() || process.env.VEO_COOKIE?.trim() || '';
  if (!token) throw new Error('Thiếu Google Flow accessToken.'); const videoModelKey = directModelKeys[model]; if (!videoModelKey) throw new Error(`${model} chưa có model key Flow Direct được xác minh. Hãy dùng Veo 3.1 - Lite [Lower Priority].`);
  const projectId = randomUUID(); const body = { mediaGenerationContext: { batchId: randomUUID(), audioFailurePreference: 'BLOCK_SILENCED_VIDEOS' }, clientContext: { projectId, tool: 'PINHOLE', userPaygateTier: 'PAYGATE_TIER_TWO', sessionId: `;${Date.now()}`, recaptchaContext: { token: '', applicationType: 'RECAPTCHA_APPLICATION_TYPE_WEB' } }, requests: [{ outputSpec: { resolution: 'VIDEO_RESOLUTION_720P' }, aspectRatio: aspectRatio === '16:9' ? 'VIDEO_ASPECT_RATIO_LANDSCAPE' : 'VIDEO_ASPECT_RATIO_PORTRAIT', textInput: { structuredPrompt: { parts: [{ text: prompt }] } }, videoModelKey, seed: Math.floor(Math.random() * 10_000), metadata: {} }], useV2ModelConfig: true };
  let current = await googleRequest(generateUrl, token, cookie, body, signal);
  for (let attempt = 0; attempt < 120; attempt += 1) { const entries = mediaEntries(current, projectId); const failed = entries.find((item) => ['FAILED', 'FAILURE'].includes(item.status)); if (failed) throw new Error(`Google Flow từ chối tạo video: ${failed.status}.`); const completed = entries.find((item) => ['SUCCESS', 'SUCCESSFUL'].includes(item.status)); const mediaUrl = completed?.url || (completed ? findDownloadUrl(current) : ''); if (mediaUrl) { const response = await fetch(mediaUrl, { signal, headers: { Authorization: `Bearer ${token}`, ...(cookie ? { Cookie: cookie } : {}) } }); if (!response.ok) throw new Error(`Không tải được video Flow Direct (HTTP ${response.status}).`); await writeFile(outputFile, Buffer.from(await response.arrayBuffer())); return { model, taskId: completed?.name || projectId }; } const pending = entries.filter((item) => ['SCHEDULED', 'ACTIVE'].includes(item.status)); if (!pending.length) throw new Error(`Google Flow Direct không trả về trạng thái media hợp lệ: ${JSON.stringify(current).slice(0, 1200)}`); await delay(4_000, signal); current = await googleRequest(checkUrl, token, cookie, { media: pending.map((item) => ({ name: item.name, projectId: item.projectId })) }, signal); }
  throw new Error('Google Flow Direct quá thời gian xử lý video.');
}
export const generateGoogleFlowPreview = (prompt: string, outputFile: string) => generateGoogleFlowVideo(prompt, outputFile);
